export const avocadoRecipe = {
  label: 'Avocado Toast',
  image: 'path/to/avocado.png',
  ingredients: [
    { name: 'Avocado', measure: '1' },
    { name: 'Bread', measure: '2 slices' },
  ],
  instructions: ['Toast the bread.', 'Slice the avocado and spread on the bread.', 'Enjoy!'],
}

export const avocadoResponseData = {
  meals: [
    {
      idMeal: '52960',
      strMeal: 'Salmon Avocado Salad',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'British',
      strInstructions:
        'Season the salmon, then rub with oil. Mix the dressing ingredients together. Halve, stone, peel and slice the avocados. Halve and quarter the cucumber lengthways, then cut into slices. Divide salad, avocado and cucumber between four plates, then drizzle with half the dressing.\r\n\r\nHeat a non-stick pan. Add the salmon and fry for 3-4 mins on each side until crisp but still moist inside. Put a salmon fillet on top of each salad and drizzle over the remaining dressing. Serve warm.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1549542994.jpg',
      strTags: 'Paleo,Keto,LowCarbs,Salad,Alcoholic,Halloween,',
      strYoutube: 'https://www.youtube.com/watch?v=FJiu2S0Xap0',
      strIngredient1: 'Salmon',
      strIngredient2: 'Avocado',
      strIngredient3: 'Cucumber',
      strIngredient4: 'Spinach',
      strIngredient5: 'Mint',
      strIngredient6: 'Lime',
      strIngredient7: 'Honey',
      strIngredient8: 'Olive Oil',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '400g',
      strMeasure2: '3',
      strMeasure3: '1',
      strMeasure4: '400g',
      strMeasure5: '4 tbs',
      strMeasure6: 'zest and juice of 1',
      strMeasure7: '2 tsp',
      strMeasure8: '3 tbs',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/4521/salmon-avocado-and-cucumber-salad',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52853',
      strMeal: 'Chocolate Avocado Mousse',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'British',
      strInstructions:
        '1. Blend all the mousse ingredients together in your food processor until smooth. Add the cacao powder first and, as you blend, have all the ingredients to hand in order to adjust the ratios slightly as the size of avocados and bananas varies so much. The perfect ratio in order to avoid the dish tasting too much of either is to use equal amounts of both.\r\n\r\n2. Taste and add a few drops of stevia if you feel you need more sweetness.\r\n\r\n3. Fill little cups or shot glasses with the mousse, sprinkle with the cacao powder or nibs and serve.\r\n\r\nTip If you don’t have a frozen banana to hand you can just use a normal one and then chill the mousse before serving for a cooling dessert.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uttuxy1511382180.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=wuZffe60q4M',
      strIngredient1: 'Banana',
      strIngredient2: 'Cacao',
      strIngredient3: 'Avocado',
      strIngredient4: 'Honey',
      strIngredient5: 'Lemon Juice',
      strIngredient6: 'Vanilla',
      strIngredient7: 'Water',
      strIngredient8: 'Sea Salt',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1',
      strMeasure2: '3 tbsp',
      strMeasure3: '1',
      strMeasure4: '2 tblsp ',
      strMeasure5: '1 tsp ',
      strMeasure6: '1 tsp ',
      strMeasure7: '2 tbsp',
      strMeasure8: 'pinch',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.hemsleyandhemsley.com/recipe/chocolate-avocado-mousse/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
}
